### PR TITLE
Feature/shopping cart  8686dakg7

### PR DESCRIPTION
**Pull request by luiggy-mamani-jalafund**
# Author: Luiggy Mamani Condori

## What did I do?
I implemented all shopping cart functionality.
1.     Add a product to the shopping cart
2.     Edit a product from the shopping cart
3.     Delete a product from the shopping cart

Features it has:
1.     View of the cart from the navbar as a Popup and as its own page.
2.     Real-time update when editing the quantity of the cart popup.
3.     Notification balloon in the navbar that indicates the quantity of products in the cart.
4.     Validation when there is no product in the cart.

## How did I do?
Storing the data in the client's local storage and managing it with states from the frontend to update it every time an action such as adding, editing or deleting is done synchronously using a global context.

## Why did I do it?
To meet the sprint goal so that users can purchase products by first selecting them in a cart.

### CODE REVIEW

**Review by daniel-espinoza-79 — COMMENTED** [review]
[Screencast from 18-11-23 20:44:59.webm](https://github.com/zrock-dev/antwood/assets/135346738/93bcdd6a-05b5-4a4d-b432-c13be72c4560)


Can you solve this particular scroll behavior?

**Review by daniel-espinoza-79 — COMMENTED** [review]
Screenshot from 2023-11-18 20-44-08


A user should not be able to buy all the sneakers,  and there should be a limit of sneakers that a user can buy for one type of sneaker.

**Comment by luiggy-mamani-jalafund** [comment]
> Screencast.from.18-11-23.20.44.59.webm
> 
> Can you solve this particular scroll behavior?

Done

**Comment by luiggy-mamani-jalafund** [comment]
> Screenshot from 2023-11-18 20-44-08
> 
> A user should not be able to buy all the sneakers, and there should be a limit of sneakers that a user can buy for one type of sneaker.

I hadn't thought about it, I think that 10 sneakers maximum would be fine for customers who want to buy several sneakers but without removing the possibility for others to also buy.

**Review by daniel-espinoza-79 — APPROVED** [review]

**Review by JCarlosHidalgoSosa — APPROVED** [review]

**Pull request merged**
