### PR TITLE
chore : improve the style for popup that displays the unavailable sneakers

### PR DESCRIPTION
**Pull request by daniel-espinoza-79**
I improved the style of the popup to display the unavailable products
 

Screenshot from 2023-12-03 08-35-34

### CODE REVIEW

**Comment by zrock-dev** [comment]
Task linked: [CU-8686kxt2u [BUG - 41 ]When deleting a product, if the user already had the product in his cart, it disappears.](https://app.clickup.com/t/8686kxt2u)

**Comment by zrock-dev** [comment]
Hey, great job! I believe we can enhance this behavior with the following workflow:

- The admin deletes product A.
- The user receives a banner notification.
- Product A in the user's shopping cart is marked as OUT OF STOCK.

Additionally, if the user clicks "Checkout Cart," these OUT OF STOCK products will not be listed under the "YOUR CART" section.

I think that with this workflow update, the modification to the user's shopping cart is less abrupt.

**Comment by daniel-espinoza-79** [comment]
The  flow that you mention sounds good , but it implies that the images should be loaded , but they currently are deleted and to change that, I should change the backend , which I think is not a good time because it is a regression and they are going to test what they are already implementing

**Comment by zrock-dev** [comment]
Alright. Lets talk about this on the next sprint.

**Review by zrock-dev — APPROVED** [review]

**Review by VictorCespedesCC — APPROVED** [review]

**Pull request merged**
