### PR TITLE
fix: product image is cropping fixed

### PR DESCRIPTION
**Pull request by luiggy-mamani-jalafund**
# Authot: Luiggy Mamani Condori

## What did I do?
I fixed the bug when the products are rendered; some have a cropping image.

---
#8686cvhpy[CODE REVIEW]

### CODE REVIEW

**Review by VictorCespedesCC — APPROVED** [review]

**Comment by zrock-dev** [comment]
Please, fix the link to the reported bug.

**Comment by zrock-dev** [comment]
You're right, the file go.work and go.work.sum should be ignored.

Here's a more [detailed explanation](https://go.googlesource.com/proposal/+/master/design/45713-workspace.md#preventing-files-from-being-checked-in-to-repositories)


This file has been added in the commit 57ee5081b9a14836948736b81e53242e6a3f19e4, @JCarlosHidalgoSosa can you tell us if you are okay removing this file?

**Comment by zrock-dev** [comment]
Task linked: [CU-8686cvhpy BUG ID 2-Cropping of images in the product gallery affecting the entire display.](https://app.clickup.com/t/8686cvhpy)

**Comment by luiggy-mamani-jalafund** [comment]
> You're right, the file go.work and go.work.sum should be ignored.
> 
> Here's a more [detailed explanation](https://go.googlesource.com/proposal/+/master/design/45713-workspace.md#preventing-files-from-being-checked-in-to-repositories)
> 
> This file has been added in the commit [57ee508](https://github.com/zrock-dev/antwood/commit/57ee5081b9a14836948736b81e53242e6a3f19e4), @JCarlosHidalgoSosa can you tell us if you are okay removing this file?

Done

**Review by zrock-dev — APPROVED** [review]

**Comment by zrock-dev** [comment]
#8686cvhpy[MERGED]

**Pull request merged**
